### ISSUE TITLE
Shit tweak

### ISSUE THREAD

**Issue by janedut** [joey-gm/Aphrodite#2]

**Comment by janedut** [comment]
Stand with your mother

**Comment by joey-gm** [comment]
It's a global fight against authoritarian regimes. Our aspiration of democracy is genuine.
You may disagree with the ideology, but make proper arguments. Right now you're just making a fool of yourself.

**Comment by janedut** [comment]
yeah you are right




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 上午10:50
收件人:&nbsp;"joey-gm/Aphrodite"<Aphrodite@noreply.github.com&gt;;
抄送:&nbsp;"🤣"<345242281@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [joey-gm/Aphrodite] Shit tweak (#2)





 
It's a global fight against authoritarian regimes. Our aspiration of democracy is genuine.
 You may disagree with the ideology, but make proper arguments. Right now you're just making a fool of yourself.
